# Generated by Django 3.2.9 on 2022-02-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='voice',
            field=models.FileField(upload_to='static/msg-voices-to-users/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, upload_to='static/profile-images/'),
        ),
    ]
