# Generated by Django 3.2.9 on 2022-02-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220203_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='voice',
            field=models.FileField(blank=True, upload_to='static/msg-voices-to-users/'),
        ),
    ]
